### ISSUE TITLE
How to remove xcconfigs from Xcode project

### ISSUE THREAD

**Issue by tobitech** [netguru/xcconfigs#4]
Hello, I inherited a project setup with xcconfigs but would like to remove it from the project and setup build settings normally with Xcode. I tried removing the included reference to the provided config files but it affect my target builds.

**Comment by Siemian** [comment]
xcconfig files contains vital settings required for building your project. If you remove the references to xcconfigs you need to recreate the same settings manually in xcode, thus i would not recommend that. Please check [one](https://nshipster.com/xcconfig/) of many articles describing the benefits of using xconfigs.

Closing due to the issue not being connected with the repo directly.
